### ISSUE TITLE
Want to donate something

### ISSUE THREAD

**Issue by tkurbad** [gaggi/27c160-tl866-adapter#1]
Hi @gaggi,

I don't know how else to reach you, so I do it via an issue:

While searching for an open source alternative to GGlab's adapter to burn a custom Amiga Kickstart ROM with a TL866, I came across your (imho much nicer) design. So I took your gerber and ordered a board from a fab. Their minimum order quantity was 3, so I in fact ordered 3 boards.
In consequence, I also ordered 3 sets of components and yesterday populated all three boards. A test  with MX27C800 EPROMs worked out just beautifully for all three of them.

Since I now have three working adapters, but only need one, I'm planning to sell two of them on amibay.com. I'd set the price tag for each at 28 EUR + shipping, which covers my expenses, and some of my time.

Off that 28 EUR, I'd like to give 5 back to you for providing this really neat design, Problem is, I don't know how to reach you.

So, maybe, we do it in reverse and you contact me? Just google my name and location, and you'll find my email address.

Thank you and best regards,
Torsten

**Comment by gaggi** [comment]
Hi @tkurbad,
I'm glad that you've liked my design and that it could help you burn your EPROM´s.
I also feel proud that you are willing to donate something for my work, but I've had fun designing the Adapter so you really didnt have to.

If you still want to donate something please feel free to donate to any children or youth charity organization (like the children and youth hospice Balthasar which is located near me - [https://www.paypal.com/donate/?token=PhWMBeirwGfywFt8eu4u8SvHf5wc1fHMc1FCGzF4panN6IFn1PvfsjiwKPQYdiJxkdJO8m&country.x=DE&locale.x=DE](url) )

Thank you for your message, you've made my day!

Best regards
Gerrit

**Comment by tkurbad** [comment]
Hi @gaggi,

sorry for the late reply. I made a donation to the hospice.

Thank you again and best regards,
Torsten
